version: 0.2

phases:
  build:
    commands:
      - aws deploy push --application-name 0328 --s3-location s3://20250328/artifact.zip --source src
artifacts:
  files:
    - '**/*'
  base-directory: src